---
  - name:  WEBSERVER INSTALLATION AND TESTING
    hosts: localhost
    become: yes
    
    tasks:
      - name: INSTALL APACHE2
        apt: name=apache2 update_cache=yes state=latest

      - name: ENABLE MOD_REWRITE
        apache2_module: name=rewrite state=present
        notify:
          - RESTART APACHE2
      - name: TESTING THE WEBSERVER
        ansible.builtin.ping: 

    handlers:
      - name: RESTART APACHE2
        service: name=apache2 state=restarted
